### ISSUE TITLE
docker exec into a container of the aws ecs deployment

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerSwap#25]
* https://aws.amazon.com/blogs/containers/new-using-amazon-ecs-exec-access-your-containers-fargate-ec2/
* https://docs.aws.amazon.com/cli/latest/reference/ecs/execute-command.html

**Comment by sbellem** [comment]
**Problem:**
How to set the `enableExecuteCommand` attribute of a task to `true` to allow running [`aws ecs execute-command`](https://docs.aws.amazon.com/cli/latest/reference/ecs/execute-command.html)? Not sure if this can be done in the compose file by [tuning the CloudFormation template](https://docs.docker.com/cloud/ecs-integration/#tuning-the-cloudformation-template).

```shell
$ aws --profile blue ecs describe-tasks \
      --cluster "arn:aws:ecs:laniakea:1234567890:cluster/hydra" \
      --tasks 7f472e1b2c7f4982e33dcd13692f4ad0c

An error occurred (InvalidParameterException) when calling the ExecuteCommand operation: The execute command failed because execute command was not enabled when the task was run or the execute command agent isn't running. Wait and try again or run a new task with execute command enabled and try again.
```


### Resources
https://www.reddit.com/r/aws/comments/m5w2b5/amazon_ecs_now_allows_you_to_execute_commands_in/

**Comment by MrChrisRodriguez** [comment]
@sbellem Did you find an answer and/or a solution? I've been banging my head against the wall trying to figure this out.

**Comment by sbellem** [comment]
@MrChrisRodriguez Sorry, I missed your question. No I have not.
